name: numbers_trivia
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.1.3
  flutter_bloc: ^7.0.0
  equatable: ^2.0.3
  dartz: ^0.10.0
  http: ^0.13.3
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.6
  mocktail: ^1.0.3
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true


